server.port=8080

spring.application.name=api-gateway

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

legacy.monolith-url=${LEGACY_MONOLITH_URL:http://localhost:8090}

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.routes[1].id=event-service
spring.cloud.gateway.routes[1].uri=lb://event-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/events/**

spring.cloud.gateway.routes[7].id=event-service-categories
spring.cloud.gateway.routes[7].uri=lb://event-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/categories/**

spring.cloud.gateway.routes[2].id=ticket-service
spring.cloud.gateway.routes[2].uri=lb://ticket-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/tickets/**

spring.cloud.gateway.routes[3].id=booking-service
spring.cloud.gateway.routes[3].uri=lb://booking-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/bookings/**
spring.cloud.gateway.routes[3].predicates[1]=Path=/api/v1/cart/**

spring.cloud.gateway.routes[4].id=checkin-service
spring.cloud.gateway.routes[4].uri=lb://checkin-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/checkin/**

spring.cloud.gateway.routes[5].id=admin-service
spring.cloud.gateway.routes[5].uri=lb://admin-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/admin/**

spring.cloud.gateway.routes[6].id=legacy-monolith
spring.cloud.gateway.routes[6].uri=${legacy.monolith-url}
spring.cloud.gateway.routes[6].predicates[0]=Path=/event-mng/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=health,info,gateway
